Fix misformatting of token.
Daw588/stateye pull request #16
Opened 2024-01-18 18:10 UTC by GunnableScum

Changes the .ROBLOSECURITY token should it be misformatted. Will probably close #12 and #15.
[Also for issue #12, the Program runs in the Background, it has no UI and can only be ended using Task-Manager or `taskkill -f -im stateye.exe`]

2024-01-18 18:11 UTC, GunnableScum commented
(Also for context, I'm using Rust for the First time, I usually code in Java, so I had some troubles along the way but managed to do this)

2024-01-18 20:26 UTC, Daw588 requested changes
I really appreciate your help with the fix. Before I can merge this, I have left one question in my review that I would like to have it answered.

2024-01-18 20:26 UTC, Daw588 commented on src/roblox.rs
> +	let token_cookie = format!(".ROBLOSECURITY={}", token).replace(".ROBLOSECURITY=.ROBLOSECURITY=", ".ROBLOSECURITY=").replace("^", "");
Could you explain why we are removing duplicate ".ROBLOSECURITY=", is it always coming with its own ".ROBLOSECURITY=", or does this behavior vary?

2024-01-18 20:34 UTC, GunnableScum commented on src/roblox.rs
> +	let token_cookie = format!(".ROBLOSECURITY={}", token).replace(".ROBLOSECURITY=.ROBLOSECURITY=", ".ROBLOSECURITY=").replace("^", "");
I made this change because in some cases when when you copy the cookie, the ".ROBLOSECURITY=" comes with it. 

(i.e. Copy it from the Network Tab, which would look like this: 
".ROBLOSECURITY=\_^|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.^|\_[CENSORED]") 

So to answer your Question, it depends on how you, as a user would copy the cookie.

2024-01-18 20:38 UTC, GunnableScum commented on src/roblox.rs
> +	let token_cookie = format!(".ROBLOSECURITY={}", token).replace(".ROBLOSECURITY=.ROBLOSECURITY=", ".ROBLOSECURITY=").replace("^", "");
Also, if you want, I could combine the Variable Delaration and return call into a singular return call, I just used println for debugging, which is why it's there.

2024-01-19 01:15 UTC, Daw588 commented on src/roblox.rs
> +	let token_cookie = format!(".ROBLOSECURITY={}", token).replace(".ROBLOSECURITY=.ROBLOSECURITY=", ".ROBLOSECURITY=").replace("^", "");
Sorry for late reply, I had to fix my GPG key for signing commits. I have made several improvements to the pull request.

2024-01-19 01:22 UTC, merged

2024-01-19 14:45 UTC, GunnableScum commented
Thank you, have a nice day!